module.exports = {
  DUPLICATE_KEY_ERROR: "DKE",
  SOCIAL_NETWORKS_SUCH_EMAIL_ALREADY_EXISTS: "SNSEAE",
  EMAIL_NOT_VALID: "ENV",
  PHONE_NOT_VALID: "PNV",
  EMAIL_IS_EMPTY: "EIE",
  INVALID_UNRECOGNIZED_HASH: "IUH",
  FACEBOOK_TOKEN_NOT_VALID: "FBTNV",
  FACEBOOK_TOKEN_EXPIRED: "FBTE",
  THIS_EMAIL_VERIFIED: "TEV",
  EMAIL_VALIDATION_CODE_INCORRECT: "EVCI",
  USER_NOT_FOUND: "UNF"
};
